image: docker:dind

asdf-plugin-test:
  stage: test
  before_script:
    - apk update && apk add util-linux git file bash
    - git clone https://github.com/asdf-vm/asdf.git
    # Cheating...
    - export ASDF_DIR=$PWD/asdf
    - export PATH=$HOME/.asdf/shims:$PATH

  script:
    - env
    - ls -l $ASDF_DIR/asdf
    - asdf plugin-add bat https://gitlab.com/wt0f/asdf-bat.git
    - asdf list-all bat
    - asdf plugin test bat https://gitlab.com/wt0f/asdf-bat.git 'bat --version' || exit 1
