image: debian:10

stages:
  - test
  - notify

asdf-plugin-test:
  stage: test
  before_script:
    - apt update && apt install -y git curl bsdmainutils file
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh

  script:
    - asdf plugin-add bat https://gitlab.com/wt0f/asdf-bat.git
    - asdf list-all bat
    - asdf plugin test bat https://gitlab.com/wt0f/asdf-bat.git 'bat --version' || exit 1

notify_success:
  stage: notify
  image: alpine:latest
  before_script:
    - apk update && apk add curl
  when: on_success
  allow_failure: true
  script:
    - project="${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    - curl -s --form-string "token=${PUSHOVER_TOKEN}"
              --form-string "user=${PUSHOVER_USER_TOKEN}"
              --form-string "url=${CI_PIPELINE_URL}"
              --form-string "priority=-1"
              --form-string "message=Pipeline success for ${project} on ${CI_COMMIT_REF_NAME}"
              https://api.pushover.net/1/messages.json

notify_fail:
  stage: notify
  image: alpine:latest
  before_script:
    - apk update && apk add curl
  when: on_failure
  allow_failure: true
  script:
    - project="${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    - curl -s --form-string "token=${PUSHOVER_TOKEN}"
              --form-string "user=${PUSHOVER_USER_TOKEN}"
              --form-string "url=${CI_JOB_URL}"
              --form-string "priority=1"
              --form-string "message=Pipeline failure for ${project} on ${CI_COMMIT_REF_NAME}"
              https://api.pushover.net/1/messages.json
