image: debian:10

stages:
  - lint
  - test
  - notify

variables:
  PLUGIN_NAME: bat
  PLUGIN_EXEC: $PLUGIN_NAME
  SHELLCHECK_VERSION: stable

asdf-plugin-lint:
  stage: lint
  before_script:
    - apt update && apt install -y xz-utils wget
    - wget -qO- https://github.com/koalaman/shellcheck/releases/download/$SHELLCHECK_VERSION/shellcheck-$SHELLCHECK_VERSION.linux.x86_64.tar.xz | tar xJv
    - cp shellcheck-$SHELLCHECK_VERSION/shellcheck /usr/bin
  script:
    - shellcheck -x bin/* -P lib/

asdf-plugin-test:
  stage: test
  before_script:
    - apt update && apt install -y git curl bsdmainutils file
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh
  script:
    - asdf plugin-add $PLUGIN_NAME $CI_REPOSITORY_URL
    - asdf list-all $PLUGIN_NAME
    - asdf plugin test $PLUGIN_NAME $CI_REPOSITORY_URL "$PLUGIN_EXEC --version" || exit 1

notify_success:
  stage: notify
  image: alpine:latest
  before_script:
    - apk update && apk add curl
  when: on_success
  allow_failure: true
  script:
    - project="${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    - curl -s --form-string "token=${PUSHOVER_TOKEN}"
              --form-string "user=${PUSHOVER_USER_TOKEN}"
              --form-string "url=${CI_PIPELINE_URL}"
              --form-string "priority=-1"
              --form-string "message=Pipeline success for ${project} on ${CI_COMMIT_REF_NAME}"
              https://api.pushover.net/1/messages.json

notify_fail:
  stage: notify
  image: alpine:latest
  before_script:
    - apk update && apk add curl
  when: on_failure
  allow_failure: true
  script:
    - project="${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    - curl -s --form-string "token=${PUSHOVER_TOKEN}"
              --form-string "user=${PUSHOVER_USER_TOKEN}"
              --form-string "url=${CI_JOB_URL}"
              --form-string "priority=1"
              --form-string "message=Pipeline failure for ${project} on ${CI_COMMIT_REF_NAME}"
              https://api.pushover.net/1/messages.json
