image: debian:10

asdf-plugin-test:
  stage: test
  before_script:
    - apt update && apt install -y git curl bsdmainutils file
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh

  script:
    - asdf plugin-add bat https://gitlab.com/wt0f/asdf-bat.git
    - asdf list-all bat
    - asdf plugin test bat https://gitlab.com/wt0f/asdf-bat.git 'bat --version' || exit 1
