image: docker:dind

asdf-plugin-test:
  stage: test
  before_script:
    # - apk update && apk add util-linux file
    - git clone https://github.com/asdf-vm/asdf.git
    - . asdf/asdf.sh
  script:
    - asdf plugin-add bat https://gitlab.com/wt0f/asdf-bat.git
    - asdf list-all bat
    - asdf plugin test bat https://gitlab.com/wt0f/asdf-bat.git 'bat --version' || exit 1
